### ISSUE TITLE
Why did you upgrade the Android SDK version to 23?

### ISSUE THREAD

**Issue by isaacfi** [Dev-hwang/poly_geofence_service#4]
Hi @Dev-hwang,

What was the reason to upgrade to Android 23? Did you find some important issue? I'm using Android 21 in some devices,

BR.

**Comment by Dev-hwang** [comment]
I set the minimum sdk to 23 because of the stability of the permission request and foreground service. I can downgrade to 21, but I don't know what compatibility issues it will cause.

**Comment by isaacfi** [comment]
Ok, I will fork your project and test with 21, if I found something I will send you a message here.

TY

**Comment by Dev-hwang** [comment]
@isaacfi

If you use the branch below, you can also use this plugin in version 21, but stability cannot be guaranteed.

Add the following line to your `pubspec.yaml` file.

```yaml
dependency_overrides:
  flutter_foreground_task:
    git:
      url: https://github.com/Dev-hwang/flutter_foreground_task.git
      ref: minsdk_21
  fl_location:
    git:
      url: https://github.com/Dev-hwang/flutter_location.git
      path: fl_location
      ref: minsdk_21
  poly_geofence_service:
    git:
      url: https://github.com/Dev-hwang/poly_geofence_service.git
      ref: minsdk_21
```

Run the flutter command~

```
flutter clean
flutter pub get
```
